# Generated by Django 4.2.6 on 2023-11-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=False, max_length=30, verbose_name='first name'),
        ),
    ]
