# Generated by Django 4.2.6 on 2023-11-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=True, max_length=30, verbose_name='first name'),
        ),
    ]
