# Generated by Django 4.2.6 on 2024-01-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_stripe_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_id',
        ),
    ]
