# Generated by Django 4.2.6 on 2024-01-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_product_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(default='', max_length=35, null=True),
        ),
    ]
