# Generated by Django 4.2.6 on 2024-02-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
