# Generated by Django 4.2.6 on 2024-02-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='date',
        ),
    ]
