# Generated by Django 4.2.6 on 2024-02-26 18:08

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_map_alter_product_image_alter_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/images/'),
        ),
    ]
