# Generated by Django 4.2.6 on 2024-02-26 18:10

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/'),
        ),
    ]
