# Generated by Django 4.2.6 on 2024-02-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_product_image_alter_product_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_id',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
