# Generated by Django 4.2.6 on 2024-02-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_product_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
