# Generated by Django 4.2.6 on 2024-02-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_product_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_id',
        ),
    ]
